In [2]:
import numpy as np

print(np.__version__)


2.5.2


In [3]:
balances = [1750000, 800000, 3200000, 450000]

In [4]:
import numpy as np

balances = np.array([1750000, 800000, 3200000, 450000])

print(balances)

[1750000  800000 3200000  450000]


In [5]:
import numpy as np

print(np.__version__)

2.5.2


In [6]:
print('hello')

hello


In [7]:
print(type(balances))

<class 'numpy.ndarray'>


In [8]:
new_balances = balances * 1.10

print(new_balances)

[1925000.  880000. 3520000.  495000.]


In [9]:
print(balances)
print(new_balances)


[1750000  800000 3200000  450000]
[1925000.  880000. 3520000.  495000.]


In [10]:
total = np.sum(balances)

print(total)

6200000


In [12]:
average = np.mean(balances)
print(average)

1550000.0


In [16]:
highest=np.max(balances)
print("highest: ", highest)
print("lowest: ", np.min(balances))


highest:  3200000
lowest:  450000


In [17]:
numbers = np.array([100,250,400,550,700])
print(numbers)
average = np.mean(numbers)
print('average is: ', average)
print('total is: ', np.sum(numbers))
print('highest is: ', np.max(numbers))
print('lowest is: ', np.min(numbers))

[100 250 400 550 700]
average is:  400.0
total is:  2000
highest is:  700
lowest is:  100
