In [1]:
import numpy as np

print(np.__version__)


2.5.2


In [2]:
balances = [1750000, 800000, 3200000, 450000]

In [3]:
import numpy as np

balances = np.array([1750000, 800000, 3200000, 450000])

print(balances)

[1750000  800000 3200000  450000]


In [4]:
import numpy as np

print(np.__version__)

2.5.2


In [5]:
print('hello')

hello


In [6]:
print(type(balances))

<class 'numpy.ndarray'>


In [7]:
new_balances = balances * 1.10

print(new_balances)

[1925000.  880000. 3520000.  495000.]


In [8]:
print(balances)
print(new_balances)


[1750000  800000 3200000  450000]
[1925000.  880000. 3520000.  495000.]


In [9]:
total = np.sum(balances)

print(total)

6200000


In [10]:
average = np.mean(balances)
print(average)

1550000.0


In [11]:
highest=np.max(balances)
print("highest: ", highest)
print("lowest: ", np.min(balances))


highest:  3200000
lowest:  450000


In [12]:
numbers = np.array([100,250,400,550,700])
print(numbers)
average = np.mean(numbers)
print('average is: ', average)
print('total is: ', np.sum(numbers))
print('highest is: ', np.max(numbers))
print('lowest is: ', np.min(numbers))

[100 250 400 550 700]
average is:  400.0
total is:  2000
highest is:  700
lowest is:  100


In [13]:
print(numbers[-1])

700


In [14]:
print(numbers[1:4])

[250 400 550]


In [16]:
print(numbers > 400)

[False False False  True  True]


In [17]:
print(numbers[numbers>400])

[550 700]


In [18]:
sales = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [200, 300, 400]
])

print(sales)

[[100 200 300]
 [150 250 350]
 [200 300 400]]


In [22]:
print(sales[2,2])

400


In [25]:
print(sales[2,1])
print(sales[1,2])
print(sales[1])
print(sales[:, 1])
print(sales[:1, 1])

300
350
[150 250 350]
[200 250 300]
[200]


In [27]:
print(np.sum(sales, axis=0))

[ 450  750 1050]


In [28]:
print(np.sum(sales, axis=1))

[600 750 900]


In [29]:
print(np.mean(sales, axis=0))
print(np.mean(sales, axis=1))

[150. 250. 350.]
[200. 250. 300.]


In [32]:
print(np.mean(sales[2]))
print(np.mean(sales[:,2])) #mean of only third column
print(np.max(sales, axis=0))

300.0
350.0
[200 300 400]


In [33]:
np.mean(sales[:, 0])  # mean of 1st column
np.mean(sales[:, 1])  # mean of 2nd column
np.mean(sales[:, 2])  # mean of 3rd column

np.float64(350.0)

In [36]:
print(sales[sales > 300])

[350 400]


In [40]:
print(numbers[(numbers >200) & (numbers< 400)])

[250]


In [42]:
print(numbers[(numbers>200)|(numbers<600)])

[100 250 400 550 700]


In [43]:
print(np.where(numbers > 400))

(array([3, 4]),)


In [45]:
balances = np.array([500000, 1500000, 800000, 2500000])

result = np.where(balances > 2000000, "High", "Low")

print(result)

['Low' 'Low' 'Low' 'High']


In [47]:
print(sales.shape)
print(balances.shape)

(3, 3)
(4,)


In [49]:
print(sales.ndim)
print(sales.size)

2
9


In [55]:
numbers = np.array([100, 250, 400, 550, 700, 800])

new_numbers = numbers.reshape(2, 3)

print(new_numbers)
#numbers.reshape(2, 3)   # ✅ 6 elements
#numbers.reshape(3, 2)   # ✅ 6 elements
#numbers.reshape(6, 1)   # ✅ 6 elements

[[100 250 400]
 [550 700 800]]


In [56]:
print(numbers.reshape(2, -1))
print(numbers.reshape(-1, 1))

[[100 250 400]
 [550 700 800]]
[[100]
 [250]
 [400]
 [550]
 [700]
 [800]]


In [60]:
numbers = np.array([550, 100, 800, 250, 700, 400])

print(np.sort(numbers))
print(np.sort(numbers[::-1]))

[100 250 400 550 700 800]
[100 250 400 550 700 800]


In [62]:
print(np.argmax(numbers))
print(np.argmin(numbers))

2
1
