In [1]:
import numpy as np

print(np.__version__)


2.5.2


In [2]:
balances = [1750000, 800000, 3200000, 450000]

In [3]:
import numpy as np

balances = np.array([1750000, 800000, 3200000, 450000])

print(balances)

[1750000  800000 3200000  450000]


In [4]:
import numpy as np

print(np.__version__)

2.5.2


In [5]:
print('hello')

hello


In [6]:
print(type(balances))

<class 'numpy.ndarray'>


In [7]:
new_balances = balances * 1.10

print(new_balances)

[1925000.  880000. 3520000.  495000.]


In [8]:
print(balances)
print(new_balances)


[1750000  800000 3200000  450000]
[1925000.  880000. 3520000.  495000.]


In [9]:
total = np.sum(balances)

print(total)

6200000


In [10]:
average = np.mean(balances)
print(average)

1550000.0


In [11]:
highest=np.max(balances)
print("highest: ", highest)
print("lowest: ", np.min(balances))


highest:  3200000
lowest:  450000


In [12]:
numbers = np.array([100,250,400,550,700])
print(numbers)
average = np.mean(numbers)
print('average is: ', average)
print('total is: ', np.sum(numbers))
print('highest is: ', np.max(numbers))
print('lowest is: ', np.min(numbers))

[100 250 400 550 700]
average is:  400.0
total is:  2000
highest is:  700
lowest is:  100


In [13]:
print(numbers[-1])

700


In [14]:
print(numbers[1:4])

[250 400 550]


In [16]:
print(numbers > 400)

[False False False  True  True]


In [17]:
print(numbers[numbers>400])

[550 700]


In [18]:
sales = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [200, 300, 400]
])

print(sales)

[[100 200 300]
 [150 250 350]
 [200 300 400]]


In [22]:
print(sales[2,2])

400


In [25]:
print(sales[2,1])
print(sales[1,2])
print(sales[1])
print(sales[:, 1])
print(sales[:1, 1])

300
350
[150 250 350]
[200 250 300]
[200]


In [27]:
print(np.sum(sales, axis=0))

[ 450  750 1050]


In [28]:
print(np.sum(sales, axis=1))

[600 750 900]


In [29]:
print(np.mean(sales, axis=0))
print(np.mean(sales, axis=1))

[150. 250. 350.]
[200. 250. 300.]


In [32]:
print(np.mean(sales[2]))
print(np.mean(sales[:,2])) #mean of only third column
print(np.max(sales, axis=0))

300.0
350.0
[200 300 400]


In [33]:
np.mean(sales[:, 0])  # mean of 1st column
np.mean(sales[:, 1])  # mean of 2nd column
np.mean(sales[:, 2])  # mean of 3rd column

np.float64(350.0)

In [36]:
print(sales[sales > 300])

[350 400]


In [40]:
print(numbers[(numbers >200) & (numbers< 400)])

[250]


In [42]:
print(numbers[(numbers>200)|(numbers<600)])

[100 250 400 550 700]


In [43]:
print(np.where(numbers > 400))

(array([3, 4]),)


In [45]:
balances = np.array([500000, 1500000, 800000, 2500000])

result = np.where(balances > 2000000, "High", "Low")

print(result)

['Low' 'Low' 'Low' 'High']


In [47]:
print(sales.shape)
print(balances.shape)

(3, 3)
(4,)


In [49]:
print(sales.ndim)
print(sales.size)

2
9


In [55]:
numbers = np.array([100, 250, 400, 550, 700, 800])

new_numbers = numbers.reshape(2, 3)

print(new_numbers)
#numbers.reshape(2, 3)   # ✅ 6 elements
#numbers.reshape(3, 2)   # ✅ 6 elements
#numbers.reshape(6, 1)   # ✅ 6 elements

[[100 250 400]
 [550 700 800]]


In [56]:
print(numbers.reshape(2, -1))
print(numbers.reshape(-1, 1))

[[100 250 400]
 [550 700 800]]
[[100]
 [250]
 [400]
 [550]
 [700]
 [800]]


In [60]:
numbers = np.array([550, 100, 800, 250, 700, 400])

print(np.sort(numbers))
print(np.sort(numbers[::-1]))

[100 250 400 550 700 800]
[100 250 400 550 700 800]


In [62]:
print(np.argmax(numbers))
print(np.argmin(numbers))

2
1


In [65]:
random_numbers=np.random.randint(1, 101, 10)
print(random_numbers)

[32 29 29 60  6 13 77 72 93 65]


In [ ]:
np.random.seed(42) #generaes same random numbers on each run.
random_numbers=np.random.randint(1,101,10)
print(random_numbers) 

[52 93 15 72 61 21 83 87 75 75]


In [87]:
names = np.array(["Sarah", "John", "David", "Mary", "Peter"])

print(np.random.choice(names, 3))

['John' 'Mary' 'Sarah']


In [91]:
print(np.random.choice(names, 3, replace=False))

['John' 'Peter' 'David']


In [92]:
print(numbers.dtype)
print(balances.dtype)

int64
int64


In [93]:
a = np.array([100, 200, 300])
b = np.array([100.5, 200.5, 300.5])

print(a.dtype)
print(b.dtype)

int64
float64


In [94]:
day1 = np.array([100, 200, 300])
day2 = np.array([400, 500, 600])

all_transactions = np.concatenate((day1, day2))

print(all_transactions) #for concatenating transactions from different sources

[100 200 300 400 500 600]


In [95]:
transactions = np.array([100, 200, 300, 400, 500, 600])

parts = np.split(transactions, 3)

print(parts)

[array([100, 200]), array([300, 400]), array([500, 600])]


In [100]:
data = np.array([100, 200, np.nan, 400, 500])

print(data)
print(np.mean(data))
print(np.nanmean(data))

[100. 200.  nan 400. 500.]
nan
300.0


In [101]:
print(data)
print(type(data))
print(np.mean(data))
print(np.nanmean(data))

[100. 200.  nan 400. 500.]
<class 'numpy.ndarray'>
nan
300.0


In [102]:
print(np.isnan(data))

[False False  True False False]


In [103]:
print(data[np.isnan(data)])

[nan]


In [106]:
valid_data = data[~np.isnan(data)]

print(valid_data)

print("Valid values:", valid_data)
print("Average:", np.mean(valid_data))
print("Total:", np.sum(valid_data))

[100. 200. 400. 500.]
Valid values: [100. 200. 400. 500.]
Average: 300.0
Total: 1200.0


In [ ]:
data_filled = np.nan_to_num(data, nan=0)

print(data_filled)
#Important professional rule. Don't automatically replace missing data with 0 or the average.

#For example, if a bank transaction amount is missing, replacing it with 0 could create a false transaction. You first need to understand why the data is missing.

#A good workflow is: Detect → Investigate → Decide → Replace/remove → Verify

#This is exactly the kind of data-quality problem you'll encounter with real bank, telecom, government, and business datasets.

[100. 200.   0. 400. 500.]


In [109]:
data = np.array([100, 200, np.nan, 400, 500])
data_filled = np.nan_to_num(data, nan=300)

print(data_filled)

[100. 200. 300. 400. 500.]
